networks:
  treq-network:
    driver: bridge

services:
  treq-frontend:
    depends_on:
      - treq-backend
    build: ./frontend
    container_name: treq-frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/nginx/ssl/treq.key:/etc/nginx/ssl/treq.key:ro
      - ./frontend/nginx/ssl/treq.crt:/etc/nginx/ssl/treq.crt:ro
      - ./frontend/nginx/ssl/dhparam.pem:/etc/nginx/ssl/dhparam.pem:ro
    networks:
      - treq-network

  treq-backend:
    build: ./backend
    container_name: treq-backend
    depends_on:
      - treq-crypto
    networks:
      - treq-network
    volumes:
      - ./backend/flags:/app/flags

  treq-hacker:
    build: ./hacker
    container_name: treq-hacker
    networks:
      - treq-network

  treq-simulator:
    depends_on:
      - treq-frontend
      - treq-hacker
    build: ./simulator
    container_name: treq-simulator
    environment:
      HTTP_PROXY: "http://treq-hacker:8080"
      HTTPS_PROXY: "http://treq-hacker:8080"
      NO_PROXY: "localhost,127.0.0.1"
    networks:
      - treq-network

  treq-crypto:
    build: ./crypto
    container_name: treq-crypto
    environment:
      - FERNET_KEY=${FERNET_KEY}
    networks:
      - treq-network
    ports:
      - "5000:5000"
